# Model run parameters
data_dir: './data_uploads'
results_dir: './model_results'

transmission_boolean: False


# test input
nodes_area: 257020
irrgation_area_ratio: 0.1
fixed_load_rate: 3.97     # 3.97 kWh/ha*day is a quarter of the irrigation load
trans_line_m: 3855        # Because the line length is pre-solved by the assumptions and the grid planning model, so we input the number here straight forward.


# General model assumptions
num_year: 0.01369863 # this is get by 120/8760
num_hours: 120       # 5 days
num_regions: 19      # decide the region numbers, which should align with the pts_area file
i_rate: 0.15

# Solar
solar_pw_cap_kw:  [0,1,   3,   10,   100,   1000]
solar_pw_cost_kw: [0,3000,8000,22000,157000,1057000] # unit price: [4000, 3000, 2000, 1500, 1200]
annualize_years_solar: 10

# Battery
battery_cost_kwh: 250
battery_eff: 0.95              # apply both on charge and discharge
battery_p2e_ratio_range: 0.25
annualize_years_storage: 5
nominal_charge_discharge_cost_kwh: 0.001

# Diesel
diesel_cost_kw: 400
diesel_cost_liter: 1.25
liter_per_kwh: 0.094634
reserve_req: 1
diesel_eff: 0.3
annualize_years_diesel: 10

# transmission
trans_cost_kw_m: 5
# the parameters below would not be considered for the 5-days study
trans_loss: 1e-5
nominal_trans_cost_kwh: 0.001
annualize_years_trans: 20

# Flexible load & pumps
irrigation_minimum_power: 1 # Minimum operation power is 1 kW
irrigation_maximum_power: 500
first_season_start:  0
first_season_end:    4
second_season_start: 0
second_season_end:   0
water_demand_kg_m2_day: 7  # 7 mm / m2*day
water_account_days: 5      # any 5-day period, water should be enough
irrigation_kwh_p_kg: 0.000227

# Gurobi solver parameters
feasibility_tol: 0.001
solver_method: -1